### ISSUE TITLE
运行 3.x-chat 报错不知道哪里弄错了

### ISSUE THREAD

**Issue by amrzteb** [easy-swoole/demo#112]
报错信息
[FatalError][file:/var/www/html/chat-demo/demo/vendor/easyswoole/easyswoole/src/Core.php][line:273]Uncaught TypeError: Argument 2 passed to EasySwoole\EasySwoole\Core::EasySwoole\EasySwoole\{closure}() must be an instance of Swoole\Server\Task, integer given in /var/www/html/chat-demo/demo/vendor/easyswoole/easyswoole/src/Core.php:273
Stack trace:
#0 [internal function]: EasySwoole\EasySwoole\Core->EasySwoole\EasySwoole\{closure}(Object(Swoole\WebSocket\Server), 16, 5, Object(App\Task\BroadcastTask))
#1 /var/www/html/chat-demo/demo/vendor/easyswoole/easyswoole/src/ServerManager.php(109): Swoole\Server->start()
#2 /var/www/html/chat-demo/demo/vendor/easyswoole/easyswoole/src/Core.php(136): EasySwoole\EasySwoole\ServerManager->start()
#3 /var/www/html/chat-demo/demo/vendor/easyswoole/easyswoole/src/Command/DefaultCommand/Start.php(98): EasySwoole\EasySwoole\Core->start()
#4 /var/www/html/chat-demo/demo/vendor/easyswoole/easyswoole/src/Command/CommandContainer.php(44): EasySwoole\EasySwoole\Command\DefaultCommand\Start->exec(Array)
#5 /var/www/html/chat-demo/demo/vendor/easyswoole/easyswoole/src/Command/Comma

**Comment by kiss291323003** [comment]
chat这个demo，还在重构

**Comment by evalor** [comment]
已经提交代码，演示见[线上演示站](http://chat.evalor.cn/)
