### ISSUE TITLE
启动时有个报错

### ISSUE THREAD

**Issue by Double-Jin** [easy-swoole/demo#116]
当SERVER_TYPE设为EASYSWOOLE_WEB_SOCKET_SERVER就会报这个错，有没有解决方法
![image](https://user-images.githubusercontent.com/48013971/58698574-13312400-83ce-11e9-98e3-59b7721eb182.png)

**Comment by kiss291323003** [comment]
、、、、、当配置为web socket 的时候请自己注册onMessage回调。具体请看demo或者文档
