### ISSUE TITLE
缺失文件？

### ISSUE THREAD

**Issue by liuxinglei168** [easy-swoole/demo#12]
![image](https://user-images.githubusercontent.com/28724833/44000779-79cd280a-9e58-11e8-9b5a-7cca3919bc61.png)
![image](https://user-images.githubusercontent.com/28724833/44000782-81e2bc9e-9e58-11e8-9397-120cb87e170e.png)

**Comment by kiss291323003** [comment]
swoole编译的时候，加携程支持

**Comment by evalor** [comment]
启用协程Redis客户端
需要安装一个第三方的异步Redis库hiredis
请参照官方文档编译Swoole以启用协程Redis支持

链接: [Coroutine\Redis](https://wiki.swoole.com/wiki/page/589.html)
