### ISSUE TITLE
demo下载下来之后报错

### ISSUE THREAD

**Issue by uniteweiwei** [easy-swoole/demo#42]
![image](https://user-images.githubusercontent.com/19373139/48413293-42f64280-e782-11e8-91c9-8a3c524d59f0.png)
php版本:7.1.8
swoole版本4.2.7
git clone https://github.com/easy-swoole/demo.git 之后,进入目录,执行composer install加载依赖
然后运行 php easyswoole start
出现报错
![image](https://user-images.githubusercontent.com/19373139/48413476-d16ac400-e782-11e8-96b3-a1c5bdbe7f24.png)
yi已修改.env的数据库配置,无效果
![image](https://user-images.githubusercontent.com/19373139/48413595-28709900-e783-11e8-8973-08ebb8ab9196.png)

**Comment by evalor** [comment]
已修复，请重新拉取代码 [commit 71ccb3f](https://github.com/easy-swoole/demo/pull/41/commits/71ccb3f1ae09e03a15bdcd7df6115b6c42631aad)

**Comment by uniteweiwei** [comment]
![image](https://user-images.githubusercontent.com/19373139/48453490-a0c07400-e7ee-11e8-92d4-1425a9d5be06.png)
还是报错,未定义变量
