### ISSUE TITLE
热重载，修改文件后，报错Swoole\Coroutine\Channel::push(): must be called in the coroutine.

### ISSUE THREAD

**Issue by wangming123** [easy-swoole/demo#76]
使用热重载，修改文件后，报错
PHP Fatal error:  Swoole\Coroutine\Channel::push(): must be called in the coroutine. in /var/html/demo/vendor/easyswoole/http/src/Dispatcher.php on line 238

Fatal error: Swoole\Coroutine\Channel::push(): must be called in the coroutine. in /var/html/demo/vendor/easyswoole/http/src/Dispatcher.php on line 238
Error at file[/var/html/demo/vendor/easyswoole/http/src/Dispatcher.php] line[238] message:[Swoole\Coroutine\Channel::push(): must be called in the coroutine.]
PHP Fatal error:  Swoole\Coroutine\Channel::push(): must be called in the coroutine. in /var/html/demo/vendor/easyswoole/http/src/Dispatcher.php on line 238

Fatal error: Swoole\Coroutine\Channel::push(): must be called in the coroutine. in /var/html/demo/vendor/easyswoole/http/src/Dispatcher.php on line 238
Error at file[/var/html/demo/vendor/easyswoole/http/src/Dispatcher.php] line[238] message:[Swoole\Coroutine\Channel::push(): must be called in the coroutine.]

![test](https://user-images.githubusercontent.com/1289427/50722587-36e88a80-110c-11e9-8f54-0724ad89a7b5.png)

**Comment by kiss291323003** [comment]
这个是swoole的bug，请升级swoole到4.2.12以上
